name = "divine-age-rules-db"
main = "src/index.ts"
compatibility_date = "2024-12-24"
account_id = "c84e7a9bf7ed99cb41b8e73566568c75"

# Routes
routes = [
  { pattern = "age-rules.admin.divine.video/*", zone_name = "divine.video" }
]

[[d1_databases]]
binding = "DB"
database_name = "divine-age-rules-db"
database_id = "9cc1dbf4-d559-4f1e-bf5f-0bbcceef306a"

# Admin UI static assets
[assets]
directory = "./admin-ui/dist"
